{% set name = "tmtools" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tmtools-{{ version }}.tar.gz
  sha256: 06010d6c2b6272f19b86e6260ce9f3175f3b601fba46520d57a5fa3ce1d4761d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pybind11 >=2.10.4
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - tmtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jvkersch/tmtools
  summary: Python bindings around the TM-align code for structural alignment of proteins
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - asford
